// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_debug.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx_Wt97caNnMOIvizfMdw-Tu5LbpnClM4',
    appId: '1:601694030048:web:87f7ef37bb2a2690ab2885',
    messagingSenderId: '601694030048',
    projectId: 'rawrecruit-2026',
    authDomain: 'rawrecruit-2026.firebaseapp.com',
    storageBucket: 'rawrecruit-2026.firebasestorage.app',
    measurementId: 'G-Y0XWBE8BHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMl-wGqPAF3gQvNf_uLRm-SfdTBFm-4ik',
    appId: '1:601694030048:android:88f76cd8e6122564ab2885',
    messagingSenderId: '601694030048',
    projectId: 'rawrecruit-2026',
    storageBucket: 'rawrecruit-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB01X-Tq0T7EFDDKbcrzzhTY9r-5mCVT9g',
    appId: '1:601694030048:ios:e8167d48990395ffab2885',
    messagingSenderId: '601694030048',
    projectId: 'rawrecruit-2026',
    storageBucket: 'rawrecruit-2026.firebasestorage.app',
    iosBundleId: 'com.app.rawrecruit',
  );
}
